version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - redis-network

  products_parser:
    build:
      context: ./products/parser
      dockerfile: Dockerfile
    environment:
      REDIS_ADDR: "redis:6379"
      PORT: 8080
    # ports:
    #   - "8001:8080"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
      - monitoring
      - redis-network

  products_web:
    build:
      context: ./products/web
      dockerfile: Dockerfile
    environment:
      REDIS_ADDR: "redis:6379"
      PORT: 8080
    ports:
      - "8000:8080"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
      - monitoring
      - redis-network

  maps:
    build:
      context: ./maps
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      API_KEY_2GIS: ${API_KEY_2GIS}
    ports:
      - "8003:8080"
    networks:
      - app-network
      - monitoring

  optimizer:
    build:
      context: ./optimizer
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      MAPS_SERVICE_URL: http://maps:8080/
      PRODUCTS_SERVICE_URL: http://products_web:8080/
    ports:
      - "8001:8080"
    depends_on:
      - maps
      - products_web
    networks:
      - app-network
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9191:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - monitoring
  
  site:
    build:
      context: ./site
      dockerfile: Dockerfile
    environment:
      MAPS_SERVICE_URL: http://maps:8080/
      PRODUCTS_SERVICE_URL: http://products_web:8080/
      OPTIMIZER_SERVICE_URL: http://optimizer:8080/
      USER_SERVICE_URL: http://user_service:8080/
    ports:
      - "80:80"
    depends_on:
      - maps
      - products_web
      - optimizer
      - user_service
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${USER_LOGIN}
      POSTGRES_PASSWORD: ${USER_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_LOGIN} -d ${USER_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  user_service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${USER_LOGIN}:${USER_PASS}@db:5432/${USER_DB}?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8080"
    networks:
      - app-network
      - postgres-network


networks:
  app-network:
    driver: bridge
  monitoring:
  redis-network:
    driver: bridge
  postgres-network:
    driver: bridge

volumes:
  redis-data:
  grafana-data:
