global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'products_web'
    metrics_path: /metrics
    static_configs:
      - targets: ['products_web:8080']

  - job_name: 'products_parser'
    metrics_path: /metrics
    static_configs:
      - targets: ['products_parser:8080']
